name: crypinvest
description: crypinvest app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+2
environment:
  sdk: '>=3.0.6 <4.0.0'
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # manually added dependency
  get: ^4.6.1
  http:
  flutter_screenutil: ^5.9.0
  google_fonts: 5.1.0
  country_code_picker: ^3.0.0
  get_storage: ^2.0.3
  logger: ^1.1.0
  pin_code_fields: 8.0.1
  image_picker: 1.0.2
  flutter_svg:
  dropdown_button2: ^2.3.7
  iconsax: ^0.0.8
  syncfusion_flutter_charts: 22.2.8
  connectivity_plus: ^4.0.1
  flutter_spinkit: ^5.2.0
  flip_card: ^0.7.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  dotted_border: ^2.0.0+3
  flutter_inappwebview: ^5.7.2+3
  dart_code_metrics: ^4.19.2
  flutter_i18n: ^0.34.0
  walletconnect_flutter_v2: ^2.1.4
  shared_preferences: ^2.2.1
  clipboard:

dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  # rules and activating additional ones.
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
#  flutter_app_name: ^0.1.1
#  change_app_package_name: ^1.1.0

#flutter_app_name:
#  name: "CrypInvest"
flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
#  flutter packages pub run build_runner build
#  fluttergen -c pubspec.yaml  # only for mac

flutter:
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/clipart/
    - assets/icon/
    - assets/logo/
    - assets/onboard/
    - assets/contract_abi/